# Generated by Django 2.2.19 on 2023-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230304_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.URLField(unique=True),
        ),
    ]
